### ISSUE TITLE
Slider touch move event

### ISSUE THREAD

**Issue by gejza74** [newnon/SpriteBuilderX#10]
Hi, 
is it possible, cocos2d-x (newnon version 3.13.1) don't sends touch moved event,
only touch began and ended event?

**Comment by newnon** [comment]
add inside you touch event something like this 
if(event == TOUCH_BEGAN || event == TOUCH_END)
{
    your code
}

**Comment by gejza74** [comment]
I think, i wasn't clear.
The problem is: i don't get moved event.

**Comment by Anywhere-Music-Player** [comment]
```
slider->addEventListener(CC_CALLBACK_2(HelloWorld::move, this));
...
void HelloWorld::move(Ref* target, Slider::EventType type) {
```
