### ISSUE TITLE
Error when compiling with Xcode 9

### ISSUE THREAD

**Issue by meiry** [newnon/SpriteBuilderX#11]
/Users/b/Documents/spritebuilderx/SpriteBuilderX/SpriteBuilder/CCSCrollBar/
CCBPProperties.plist:0: error: failed to copy to
/Users/b/Library/Developer/Xcode/DerivedData/SpriteBuilderX-
fxfwprrikajhgbaprqmcfcickpnq/Build/Products/Debug/SpriteBuilderX.app/Contents/Resources/
CCBPProperties.plist: “CCBPProperties.plist” couldn’t be copied to “Resources” because an
item with the same name already exists.

**Comment by Anywhere-Music-Player** [comment]
I’m using it with Xcode 9 without any problems. Need mire info.

**Comment by meiry** [comment]
sorry , i removed the temp directory in Xcode/DerivedData and every thing working fine
after compiling again
