### ISSUE TITLE
Why Inspector view  had 'Check Box' on left-Top?

### ISSUE THREAD

**Issue by zhouxiaoxiaoxujian** [newnon/SpriteBuilderX#13]
why so many Inspector views like 'InspectorBlendmode.xib' had 'Check Box" on left-top?

**Comment by Anywhere-Music-Player** [comment]
Show me.

**Comment by zhouxiaoxiaoxujian** [comment]
![untitled](https://user-images.githubusercontent.com/433075/38479817-57367c4a-3bf4-11e8-92d8-2433b684c8e2.jpeg)

**Comment by newnon** [comment]
This check box enable property parametrization. It is useful if you place this prefab inside another and want to control this property from parent prefab.
