### ISSUE TITLE
Scene not showing

### ISSUE THREAD

**Issue by BobyIlea** [newnon/SpriteBuilderX#14]
Hey everyone, I have cloned the SBX repo and checkout SpriteBuilderX branch. After fixing a few minor build errors I managed to make SBX run, but it doesn't seem to work correctly. First of all, the scene does not show on screen:
![Screenshot 2019-10-27 at 18 56 52](https://user-images.githubusercontent.com/3233577/67638318-d4a38500-f8eb-11e9-9b94-591b1ae119df.png)

Any idea why? I am building using Xcode 11.0

**Comment by Anywhere-Music-Player** [comment]
This is fixed in my fork in default branch.
