### ISSUE TITLE
xcode build can't find Chipmunk project.

### ISSUE THREAD

**Issue by cyutao7545** [newnon/SpriteBuilderX#3]
clang: error: no such file or directory: '/Users/chenyutao/Desktop/projects/SpriteBuilderX/SpriteBuilder/libs/cocos2d-iphone/external/Chipmunk/src/cpHashSet.c'
clang: error: no input files

**Comment by volodymyr-vestasoft** [comment]
I just cloned:

![db85a2833cde9f46d3c2cf252c1581322a3b12cb](https://cloud.githubusercontent.com/assets/24410648/22791381/d7c4ee92-eef1-11e6-9e6e-3937e5284b1a.png)

And got: "Build Succeeded". You are doing something wrong.

**Comment by Anywhere-Music-Player** [comment]
I just cloned:

![d7c4ee92-eef1-11e6-9e6e-3937e5284b1a](https://cloud.githubusercontent.com/assets/3391456/22798598/56e63442-ef0b-11e6-9a14-f887fead8c9c.png)

And got: "Build Succeeded". You are doing something wrong.

**Comment by cyutao7545** [comment]
ok i'll try it again.

**Comment by cyutao7545** [comment]
i don't use SourceTree to clone, when use ssh git clone and must run "git submodule update --init --recursive" not "git submodule update --init", and finally build project success.
