### ISSUE TITLE
Gradient Node

### ISSUE THREAD

**Issue by gejza74** [newnon/SpriteBuilderX#7]
Hi,

if i create a gradient node, then by load of scene i get error:
no corresponding node loader for CCNodeGradient
Assert failed: The object should not be nullptr

**Comment by Anywhere-Music-Player** [comment]
Which cocos2d-x u're using?

**Comment by gejza74** [comment]
I use "newnon/cocos2d-x/cocos" 3.13 precompiled cocos2d-x lib

**Comment by newnon** [comment]
Fixed in last commits of 3.13.1

**Comment by gejza74** [comment]
Thanks, but be careful, in 3.13.1 tools/cocos2d-console is empty.
