### ISSUE TITLE
Text input

### ISSUE THREAD

**Issue by gejza74** [newnon/SpriteBuilderX#8]
Hi,

i try to implement some text input.
I tried with Text Field, and with Edit Box also.
The Text Field stays invisible, that means it's not working.
The Edit Box crashes by load of the scene.

Is there any text input possibility implemented?

Thanx

**Comment by newnon** [comment]
Edit Box is fully functional but you must set correct sprite frame for background

**Comment by gejza74** [comment]
Yes, You have right, Edit Box works.
Just one little issue yet, on Android how you know, if the text input ended, and (or) hide the virtual keyboard? Thank you

**Comment by gejza74** [comment]
I think i found it, by UIEditBoxTest.

**Comment by newnon** [comment]
yes
