### ISSUE TITLE
Animation manager, loop

### ISSUE THREAD

**Issue by gejza74** [newnon/SpriteBuilderX#9]
Hi,  i try to play a frame animation of a node, the animation plays, but i don't find any solution to play it in loop. The animation is created in SpriteBuilderX.

I try it so:
void Answer1::runAnimation(std::string animationName, bool loop) {
  // we have to first stop any of the character's running actions so that we can start a new one
  this->stopAllActions();

  // the animation manager of each node is stored in the 'animationManager' property
  CCBAnimationManager* animationManager = CCBAnimationManager::fromNode(this);
  // timelines can be referenced and run by name
  //animationManager->runAnimationsForSequenceNamed(animationName.c_str());
  // OR JUST ANOTHER EXAMPLE
  animationManager->runAnimationsForSequenceNamedTweenDuration(animationName.c_str(), 3.0f);
}

How it possible to play it in loop?
Thank you

**Comment by newnon** [comment]
it is 2 variants 
1 - In SpriteBuilder set chained timeline to itself and it will play until you stop them
2 - You can add callback and run this animation again
runAnimationsForSequenceNamed(const char *pName, const std::function<void(cocos2d::Node*, AnimationCompleteType)> &**callback** = nullptr);

**Comment by gejza74** [comment]
Thanx, it works.
